exports.CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY || "753357197199188";
exports.CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET || "5I8U9eRQVs1-Oki2X0RmO1FK9dg";
exports.CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME || "drkp2wxz4";
